### ISSUE TITLE
VM Abort due to getIcon call

### ISSUE THREAD

**Issue by UndeadZeratul** [HDest-Community/ZRadarHD#1]
Paranthropus reported this on the Discord server, it seems when starting a new level with the ZRadar item in an Assault Pack, that it caused a VM Abort.  Looking at the error, though, it seems to call `getIcon()` at some point during the consolidation process?

![image](https://github.com/HDest-Community/ZRadarHD/assets/6988914/5c21a4ae-92d5-476f-8df0-e2560276cc55)

**Comment by UndeadZeratul** [comment]
Hmm, upon closer inspection, something is calling `getIcon()`, which calls the radar's `getPickupSprite()` method, which throws the error...  Not sure where the problem is coming from, I thought we got rid of the need for the GetIcon port?

**Comment by Cryomundus** [comment]
Decided to use an different method for getting the pickup sprite. It's not exactly the greatest, but it no longer crashes on level transition. Still not terribly sure what was causing the original crash, however. 

Not the most familiar with how hdest gets its icons, so if you or someone else would like to update it, go ahead. I'll eventually return to this and see if I can polish it up, but I don't mind if someone else wishes to do so.
